name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: false
    default: ""
  
runs:
  using: composite
  steps:
    - run: echo line 1
      shell: bash
      if: ${{ inputs.MY_NAME }}
    - run: echo line 2
      shell: bash

  

branding:
  icon: "mic"
  color: "purple"