name: A workflow for my Hello World file
on: push

env:
  TEST_VAR: ${{ true }}

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
          test_var: ${{ env.TEST_VAR }}